version: 2.0

aliases:
  - &nodejs-docker-image
    - image: circleci/node:10.16.3
  
  - &restore_cache
    restore_cache:
      name: Restore node_modules cache
      keys:
        - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
        - node-v1-{{ .Branch }}-
        - node-v1-

jobs:
  setup:
    docker: *nodejs-docker-image
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install NPM
          command: |
            echo 'Installing dependencies'
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            npm install
      - save_cache: 
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  tslint: 
    docker: *nodejs-docker-image
    steps:
      - checkout
      - *restore_cache
      - run:
          name: TSLint
          command: npm run tslint
      - run:
          name: Check formatting (Prettier)
          command: npm run check-formatting        

  unit-tests:
    docker: *nodejs-docker-image
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run unit tests
          command: npm run test:ci
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

  e2e-tests:
    docker: *nodejs-docker-image
    steps:
      - checkout
      - *restore_cache
      - run:
          name: E2E Tests
          command: echo "E2E tests running"

  build-and-push-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Building and pushing image to Docker Hub
          command: |
            TAG_VERSION=$(node -p -e "require('./package.json').version")
            echo '$TAG_VERSION' $TAG_VERSION     
            echo $NPM_TOKEN
            IMAGE_NAME=solidstudio/web
            docker build --build-arg NPM_TOKEN=$NPM_TOKEN -t $IMAGE_NAME:$TAG_VERSION -t $IMAGE_NAME:latest .
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
            docker push $IMAGE_NAME:$TAG_VERSION
            docker push $IMAGE_NAME:latest

  publish:
    docker: *nodejs-docker-image
    steps:
      - checkout
      - run:
          name: Publishing new version
          command: echo "Publishing"

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup:
          context: SolidStudio
      - tslint:
          requires:
            - setup
      - unit-tests:
          requires:
            - setup
      - e2e-tests:
          requires:
            - setup
      - build-and-push-docker-image:
          context: SolidStudio
          requires:
            - tslint
            - unit-tests
            - e2e-tests
          filters:
            branches:
              only: master 
      - publish:
          context: SolidStudio
          requires:
            - build-and-push-docker-image
          filters:
            branches:
              only: master